matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - sh prepare-sketch.sh
        - sh init-sketch.sh
      script:
        - sh increment-version.sh
        - sh inject-version.sh
        - sh build-sketch.sh
